/**
 * API
 * API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FileDto } from './fileDto';

export interface AuthUpdateDto { 
    photo: FileDto;
    firstName: string;
    lastName: string;
    password: string;
    oldPassword: string;
}