/**
 * API
 * API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type RoleEnum = 1 | 2;

export const RoleEnum = {
    Admin: 1 as RoleEnum,
    User: 2 as RoleEnum
};