/**
 * API
 * API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type StatusEnum = 1 | 2;

export const StatusEnum = {
    Active: 1 as StatusEnum,
    InActive: 2 as StatusEnum
};