/**
 * API
 * API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FileType } from './fileType';
import { Role } from './role';
import { Status } from './status';

export interface User { 
    id: string | number;
    email: string;
    password?: string;
    previousPassword?: string;
    provider: string;
    socialId?: string;
    firstName?: string;
    lastName?: string;
    photo?: FileType;
    address?: string;
    phone?: string;
    role: Role;
    status: Status;
    createdAt: Date;
    updatedAt: Date;
    deletedAt?: Date;
}